[params]
  # Theme customization
  brand_color = "#2563eb"  # Blue-600
  accent_color = "#7c3aed"  # Violet-600
  
  # Typography
  font_family = "Inter"
  heading_weight = 900
  
  # Features
  enable_search = true
  enable_dark_mode = true
  show_reading_time = true
  
  # CTA Configuration
  cta_type = "newsletter"  # newsletter | community | creator
  
  # Featured content (manual selection)
  featured_limit = 6
  description = "Creatore di contenuti, newsletter, podcast e video. Trasforma la tua passione in una professione con strategie, strumenti e tecniche per diventare un content creator di successo."
  
  # Author configuration (replaces deprecated .Site.Author)
  [params.author]
    name = "Content Creator"
    email = "creator@example.com"
  
  # Social links
  [params.social]
    twitter = ""
    instagram = ""
    youtube = ""
    linkedin = ""
    github = ""

[markup]
  [markup.highlight]
    style = "github"
    lineNos = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

baseURL = "http://localhost:1313"
title = "Content Creator Hub"
languageCode = "it-IT"
defaultContentLanguage = "it"

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  
[outputs]
  home = ["HTML", "RSS", "JSON"]

[languages]
  [languages.it]
    languageName = "Italiano"
    title = "Content Creator Hub"
    description = "Creatore di contenuti, newsletter, podcast e video. Trasforma la tua passione in una professione con strategie, strumenti e tecniche per diventare un content creator di successo."
    weight = 1
    
  [languages.en]
    languageName = "English"
    title = "Content Creator Hub"
    description = "Content creator, newsletters, podcasts and videos. Transform your passion into a profession with strategies, tools and techniques to become a successful content creator."
    weight = 2

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"